# Generated by Django 2.2 on 2020-07-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='posted_by',
        ),
    ]
