# Generated by Django 2.2 on 2020-08-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='showtime',
        ),
    ]
