# Generated by Django 3.0.6 on 2020-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20200802_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
