# Generated by Django 3.0.8 on 2020-07-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_showtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinoroom',
            name='room',
            field=models.CharField(default='A1', max_length=2),
        ),
    ]
