# Generated by Django 3.0.6 on 2020-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_auto_20200802_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
