# Generated by Django 2.2 on 2020-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20200801_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
