# Generated by Django 3.0.8 on 2020-07-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20200731_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=1),
        ),
    ]
