# Generated by Django 2.2 on 2020-08-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_showtime_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
