# Generated by Django 3.0.8 on 2020-08-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_movie_video_url'),
        ('app_one', '0006_auto_20200731_2312'),
    ]

    operations = [
    ]
