# Generated by Django 3.0.6 on 2020-08-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_auto_20200804_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
